name: Build & Deploy

on:
    push:
        branches:
            - test
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'test'
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          
          script: |
            cd /var/www/test/DDV2
            git pull origin test
            composer install
            php artisan migrate
            echo 'Deployment successful to digital ocean'
            
