name: Test Deploy
on:
  push:
    branches: [test]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd /var/www/test/DDV2/
            git pull origin test
            php artisan migrate
            composer install
            echo 'Deployed to test directory'
